### ISSUE TITLE
Outputs is left as array instead of string

### ISSUE THREAD

**Issue by dleen** [AnswerDotAI/execnb#32]
Compared to `nbformat` the outputs field of `execnb` remains as an array of strings (for compatability with json) instead of being squashed to a single string. 

This prevents `execnb` from being a drop in replace for `nbformat` at least when using with the `nbdime` library.

For example see:

https://github.com/dleen/notebook-examples/blob/main/00_core.ipynb

The logic in nbformat for splitting/joining: https://github.com/jupyter/nbformat/blob/640a0c6830bb6dc0ef963a8caab377d89ed24c6a/nbformat/v4/rwbase.py#L26

**Comment by jph00** [comment]
Sorry @dleen I missed this (at-mention me on issues to ensure I don't miss them!)

Any thoughts about how to get the best of both worlds here?
