### ISSUE TITLE
displaying plots using matplotlib in a notebook after `CaptureShell()`

### ISSUE THREAD

**Issue by radekosmulski** [AnswerDotAI/execnb#44]
Once I instantiate a `CaptureShell` in a notebook, I can no longer display plots.

![image](https://user-images.githubusercontent.com/2444926/203214780-939b36e1-3946-4243-8f24-a799c7c4367d.png)

There seems to be quite a bit of functionality in code relating to this, but I am not sure how I am supposed to use it. Could I please ask if there is anything I can call/pass somewhere in order to be able to plot from the host notebook?

Thank you!

**Comment by jph00** [comment]
Fixed now!
